name: GitHub Pages Deployment

on:
  push:
    branches:
      - main  # Or your default branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3  # Ensures you're using a compatible Node.js version
        with:
          node-version: '16'  # Or '20' if preferred

      - name: Install dependencies and build site
        run: |
          npm install
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4  # Updated to v4
        with:
          github_token: ${{ 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 }}
          publish_dir: ./public  # Adjust if necessary for your project structure
